# Generated by Django 4.0.2 on 2022-02-14 20:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Lista_de_produtos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Loja',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_loja', models.CharField(max_length=20)),
                ('endereco', models.CharField(max_length=100)),
                ('complemento', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Rede',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_rede', models.CharField(max_length=100)),
                ('cnpj', models.CharField(max_length=14)),
            ],
        ),
        migrations.CreateModel(
            name='Venda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('diaehora', models.DateTimeField(auto_now_add=True)),
                ('lista_de_produtos', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='app.lista_de_produtos')),
            ],
        ),
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_produto', models.CharField(max_length=20)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=5)),
                ('loja', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='app.loja')),
            ],
        ),
        migrations.CreateModel(
            name='Pessoa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=100)),
                ('role', models.IntegerField(choices=[(1, 'ADMINISTRADOR'), (2, 'OPERADOR'), (3, 'GERENTE')])),
                ('rede', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='app.rede')),
            ],
        ),
        migrations.AddField(
            model_name='loja',
            name='rede',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='app.rede'),
        ),
        migrations.AddField(
            model_name='lista_de_produtos',
            name='produto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='app.produto'),
        ),
    ]
