# Generated by Django 4.0.2 on 2022-02-14 22:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ListaDeProdutos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='app.produto')),
            ],
        ),
        migrations.RemoveField(
            model_name='venda',
            name='lista_de_produtos',
        ),
        migrations.DeleteModel(
            name='Lista_de_produtos',
        ),
        migrations.AddField(
            model_name='listadeprodutos',
            name='venda',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='app.venda'),
        ),
    ]
