# Generated by Django 4.0.2 on 2022-02-15 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_listadeprodutos_remove_venda_lista_de_produtos_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='venda',
            name='total',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=7),
        ),
    ]
