# Generated by Django 4.0.2 on 2022-02-15 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_venda_total'),
    ]

    operations = [
        migrations.AddField(
            model_name='listadeprodutos',
            name='quantidade',
            field=models.IntegerField(default=1, max_length=200),
        ),
    ]
